"""
Django settings for shubik_shop project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from os.path import join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#ax-5eq$oz*^#p$_c9^@og#)=5@rg7#ms3e_w&^fyy+n+h1)dt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'storages',
    'compras',
    'usuario',
    'productos',
    'tiendas',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    'login',
    'notificacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'Authorization',
    'X-Requested-With',
    'accept',
    'origin',
    'Access-Control-Allow-Origin',
    'X-CSRFToken',
]

CORS_ALLOW_ALL_ORIGINS = True  # Permitir todos los orígenes

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'shubik_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR, 'vistas')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shubik_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
#respaldo de la base de datos
DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': 'prueba',
         'USER': 'postgres',
         'PASSWORD': '1234',
         'HOST': '190.44.152.202',  # o la dirección de tu servidor de base de datos
         'PORT': '5432',        #puerto por defecto de PostgreSQL
     }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'shubik',  # El nombre de tu base de datos
#        'USER': 'postgres',
#        'PASSWORD': '1234567890.a',
#        'HOST': 'shubik.postgres.database.azure.com',
#        'PORT': '5432',  # Puerto por defecto
#        'OPTIONS': {
#            'sslmode': 'require',  # Opcional, pero recomendado para mayor seguridad
#        },
#    }
#}


#DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'
#AZURE_ACCOUNT_NAME = 'shubikimagenes'  # Tu nombre de cuenta de Azure
#AZURE_CONTAINER = 'fotos'  # Nombre del contenedor
#AZURE_ACCOUNT_KEY = 'TVmYEyhm0n6puZ4SyIoYJA4QjblRUPxhukIco0F0OCQAOb6x26PjFBbAiixAGPz2iUZTUQ07KCTA+AStSX1Y5A=='  # Tu clave de cuenta
#AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
#AZURE_STORAGE_CONNECTION_STRING = 'DefaultEndpointsProtocol=https;AccountName=shubikimagenes;AccountKey=TVmYEyhm0n6puZ4SyIoYJA4QjblRUPxhukIco0F0OCQAOb6x26PjFBbAiixAGPz2iUZTUQ07KCTA+AStSX1Y5A==;EndpointSuffix=core.windows.net'
#AZURE_CONTAINER_NAME = 'fotos'
MEDIA_URL = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = '/media/'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # Duración del token de acceso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # Duración del token de refresh
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Usamos el SECRET_KEY de tu configuración
    'AUTH_HEADER_TYPES': ('Bearer',), # Los tokens JWT se envían en los headers como 'Bearer <token>'
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Asegúrate de tener esto configurado
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Si tienes un directorio "static" para archivos estáticos

# Configura la URL para los archivos multimedia
MEDIA_URL = '/media/'

# Configura el directorio donde se almacenarán los archivos multimedia
MEDIA_ROOT = join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Esto es para los filtros
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}
