# Generated by Django 5.1.1 on 2024-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
