import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { AuthProvider } from "@/auth/authContext";



export const metadata: Metadata = {
  title: "Shubik Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>


  );
}
